backend:
  name: git-gateway
  repo: Michael-Wayne-Wells/lumiri-gatsby-site
  commit_messages:
  create: "Create {{collection}} “{{slug}}”"
  update: "Update {{collection}} “{{slug}}”"
  delete: "Delete {{collection}} “{{slug}}”"
  uploadMedia: "[skip ci] Upload “{{path}}”"
  deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/about/drschatz.md"
        label: "About Dr. Tiffany Schatz"
        name: "about dr. schatz"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/index.md"
        label: "Index"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Featured, name: featured, widget: text },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/patientinfo/index.md"
        label: "Patient Info"
        name: "patient information"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "base",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/patientinfo/prepare.md"
        label: "Preparing for Surgery"
        name: "prepare"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "base",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/patientinfo/procedures.md"
        label: "Subspecialties and Areas of Clinical Concentrations"
        name: "specialties"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "base",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
